### ISSUE TITLE
ERROR: Failed to build gem native extension

### ISSUE THREAD

**Issue by 3con** [yosisa/fluent-plugin-tail-ex#1]
I get the following error:

sudo gem install fluent-plugin-tail-ex
Building native extensions.  This could take a while...
ERROR:  Error installing fluent-plugin-tail-ex:
    ERROR: Failed to build gem native extension.

```
/usr/bin/ruby1.8 extconf.rb
```

Gem files will remain installed in /usr/lib/ruby/gems/1.8/gems/msgpack-0.5.5 for inspection.
Results logged to /usr/lib/ruby/gems/1.8/gems/msgpack-0.5.5/ext/msgpack/gem_make.out

I also tired `sudo apt-get install ruby-1.8-dev` but that is already installed.

**Comment by yosisa** [comment]
Hi

I think this is not a fluent-plugin-tail-ex error.
Please install fluentd first for troubleshooting.

Since recent version of fluentd requires Ruby version >= 1.9.2,
I suggest you to upgrade Ruby before trying to install fluentd.

**Comment by yosisa** [comment]
I close this issue because there is no response.
