### ISSUE TITLE
What is refresh_interval?

### ISSUE THREAD

**Issue by erbdex** [yosisa/fluent-plugin-tail-ex#5]
Is it the time in which the path with wildcard will be resolved again?
Use case-

My config contains- 
`path /tmp/app/*.log`

At time t=0, there are two files and both get resolved and tailed by tail_ex.
If at time t=10min, a third .log file appears in the directory, will it be tailed?

**Comment by yosisa** [comment]
> Is it the time in which the path with wildcard will be resolved again?

Yes.

> If at time t=10min, a third .log file appears in the directory, will it be tailed?

Yes, but actual time that start tailing the new file depends on `refresh_interval`.
For example, the new file will be tailed at t=10min where refresh_interval is 600 (seconds),
but the new file will be tailed at t=15min if refresh_interval is 900 (seconds).
